### ISSUE TITLE
From the original creators of this tool: Please take this down

### ISSUE THREAD

**Issue by haze** [Ezzpify/FindLowDigAccounts#1]
Because I did not have a copyright on the code me, phoenixdoom, latematt, banksy and apteryx wrote I ask you to take this port down.

**Comment by apertix** [comment]
Hi, I'm apteryx. Anyway, what he means by copyright is the lack of license on our project.

https://github.com/hvze/steam-gen

No license (#NoLicense)

```
If source code does not carry a license to give users the four essential freedoms, then unless it has been explicitly and validly placed in the public domain, it is not free software.

Some developers think that code with no license is automatically in the public domain. That is not true under today's copyright law; rather, all copyrightable works are copyrighted by default. This includes programs. Absent a license to grant users freedom, they don't have any. In some countries, users that download code with no license may infringe copyright merely by compiling it or running it.

In order for a program to be free, its copyright holders must explicitly grant users the four essential freedoms. The document with which they do so is called a free software license. This is what free software licenses are for.

Some countries allow authors to put code in the public domain, but that requires explicit action. If you wish to do that, the method we recommend is to use CC0, which also works in other countries by putting on a license that is more or less equivalent to public domain. However, in most cases it is better to copyleft your code to assure that freedom reaches all users of the code.

Code written by employees of the US government is a special exception, since US copyright law explicitly puts that in the public domain; but this does not apply to works that the US pays a company to write. It also does not apply to other countries, many of which do allow the state to have a copyright on government writings.
```

As a fellow developer we ask you to remove this project and any where you've uploaded it.

**Comment by Ezzpify** [comment]
It's simply just a port, though.
You originally released the code, so I don't see why you would have a problem with the code being public? I don't do this for money obviously, I just like to write code.

If you can explain why you have a problem with this release, then I will take it down.

**Comment by Ezzpify** [comment]
Additionally, this is a "port" from http://pastie.org/private/0sk2vnagrpttaievoztpq that was posted on a public forum (thus does not have a licence). 
I did not port the project you're linking.

**Comment by haze** [comment]
That is an earlier version of our project: You need the say from us to port it.

**Comment by apertix** [comment]
I mean, I'm fine with it as long as the people who were in the project are credited. Hvze, myself, latematt.

**Comment by Ezzpify** [comment]
Read last comment

**Comment by Ezzpify** [comment]
I did credit the one that posted the piece of code, as you can see on the main page of this repo

**Comment by haze** [comment]
However that piece of code originated from me.

**Comment by Ezzpify** [comment]
Okay, but then again you don't really have any ground to stand on here.
However I am a nice guy, so if you can give me a valid reason as to why you want this project taken down, then I will take it down.

I have a hard time to see it being because you want to make money from the method, since one of you posted it on a public forum for thousands to see.

**Comment by haze** [comment]
1. because it was a branched idea from phoenixdoom-- our code is merely identical
2. you don't have to take this port down, just mention my project and its original contributors

**Comment by Ezzpify** [comment]
Added credits where credits are due!

**Comment by apertix** [comment]
Thank you.

**Comment by ygstr** [comment]
please add a license so I can compile this with your permission

**Comment by Ezzpify** [comment]
Added @ygstr
